server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /ems


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 12345678

mybatis:
  configuration:
    map-underscore-to-camel-case: true


